version: '3'
services:
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../web/build:/var/www/fussel:ro
      # - ./build:/var/www/fussel:ro
    ports:
      - "8080:80"